[package]
name = "cosmos-sdk-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# NEAR SDK for smart contract development
near-sdk = { version = "5.1.0", features = ["legacy"] }

# Use workspace dependencies for consistency
borsh = { workspace = true }  
serde = { workspace = true }
serde_json = { workspace = true }
ed25519-dalek = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
chrono = { workspace = true }

# NEAR-specific dependencies
schemars = "0.8"

[dev-dependencies]
# Use workspace dependencies for testing
near-workspaces = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
reqwest = { workspace = true }
base64 = { workspace = true }

# NEAR SDK testing features
near-sdk = { version = "5.1.0", features = ["unit-testing"] }

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true