# IBC Relayer Configuration for Local Development
# Uses local wasmd testnet instead of public testnets

[global]
log_level = "info"
max_retries = 3
retry_delay_ms = 1000
health_check_interval = 30

# Chain configurations
[chains.near-testnet]
chain_type = "near"
chain_id = "near-testnet"
rpc_endpoint = "https://rpc.testnet.near.org"

[chains.near-testnet.config]
type = "near"
# Our deployed Cosmos SDK contract
contract_id = "cosmos-sdk-demo.testnet"
signer_account_id = "cuteharbor3573.testnet"
network_id = "testnet"
# private_key = "ed25519:..." # Set via environment variable

# Local wasmd testnet - controlled and reliable
[chains.wasmd-local]
chain_type = "cosmos"
chain_id = "wasmd-testnet"
rpc_endpoint = "http://localhost:26657"
ws_endpoint = "ws://localhost:26657/websocket"

[chains.wasmd-local.config]
type = "cosmos"
address_prefix = "wasm"
gas_price = "0.025stake"
trust_threshold = "1/3"
trusting_period_hours = 336

# Connection configurations for local testing
[[connections]]
id = "connection-0"
src_chain = "near-testnet"
dst_chain = "wasmd-local"
src_client_id = "07-tendermint-0"
dst_client_id = "07-near-0"
auto_relay = true

# Metrics and monitoring
[metrics]
enabled = true
host = "127.0.0.1"
port = 9090