# IBC Relayer Configuration for NEAR-Cosmos Bridge

[global]
log_level = "info"
max_retries = 3
retry_delay_ms = 1000
health_check_interval = 30

# Chain configurations
[chains.near-testnet]
chain_type = "near"
chain_id = "near-testnet"
rpc_endpoint = "https://rpc.testnet.near.org"

[chains.near-testnet.config]
type = "near"
# Our deployed Cosmos SDK contract
contract_id = "cosmos-sdk-demo.testnet"
signer_account_id = "cuteharbor3573.testnet"
network_id = "testnet"
# private_key = "ed25519:..." # Set via environment variable

[chains.cosmoshub-testnet]
chain_type = "cosmos"
chain_id = "provider"
rpc_endpoint = "https://rest.provider-sentry-01.ics-testnet.polypore.xyz"
ws_endpoint = "wss://rpc.provider-sentry-01.ics-testnet.polypore.xyz/websocket"

[chains.cosmoshub-testnet.config]
type = "cosmos"
address_prefix = "cosmos"
gas_price = "0.025uatom"
trust_threshold = "1/3"
trusting_period_hours = 336  # 14 days
# Keys will be loaded from encrypted keystore

# Connection configurations
[[connections]]
id = "connection-0"
src_chain = "near-testnet"
dst_chain = "cosmoshub-testnet"
src_client_id = "07-tendermint-0"
dst_client_id = "07-near-0"
auto_relay = true

# Metrics configuration
[metrics]
enabled = true
host = "127.0.0.1"
port = 3001